# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'modalTeste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for modalTeste

  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'RxAlamofire'

  target 'modalTesteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'modalTesteUITests' do
    # Pods for testing
  end

end
